<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cube_robot">

  <!-- Define parameters -->
  <xacro:property name="base_length" value="1"/>
  <xacro:property name="base_width" value="1"/>
  <xacro:property name="base_height" value="1"/>
  
  <xacro:property name="leg_length" value="0.5"/>
  <xacro:property name="leg_width" value="0.5"/>
  <xacro:property name="leg_height" value="2"/>

  <!-- Define base -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.0833333" ixy="0" ixz="0" iyy="0.0833333" iyz="0" izz="0.0833333"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1"/>
      </material>
    </visual>
  </link>

  <!-- Define legs -->
  <xacro:macro name="leg" params="prefix x_offset">
    <link name="${prefix}_leg_link">
      <inertial>
        <origin xyz="0 0 ${-base_height/2}" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.0138889" ixy="0" ixz="0" iyy="0.0138889" iyz="0" izz="0.0138889"/>
      </inertial>
      <collision>
        <origin xyz="0 0 ${-base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${leg_length} ${leg_width} ${leg_height}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${-base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${leg_length} ${leg_width} ${leg_height}"/>
        </geometry>
        <material name="blue">
          <color rgba="0.1 0.1 0.8 1"/>
        </material>
      </visual>
    </link>
  </xacro:macro>

  <!-- Instance legs -->
  <xacro:leg prefix="left" x_offset="-${base_length/2}" />
  <xacro:leg prefix="right" x_offset="${base_length/2}" />

  <!-- Joint definition -->
  <joint name="left_leg_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_leg_link"/>
    <origin xyz="${-base_length/2-leg_length/2} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="1.0" lower="-1.57" upper="1.57"/>
  </joint>
  
  <joint name="right_leg_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_leg_link"/>
    <origin xyz="${base_length/2+leg_length/2} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="1.0" lower="-1.57" upper="1.57"/>
  </joint>

  <xacro:include filename="bipedal.ros2_control.xacro" />

</robot>
