publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 1
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7", "pos8", "pos9"]
    pos1: [0]
    pos2: [0.785]
    pos3: [1.57]
    pos4: [2.36]
    pos5: [3.14]
    pos6: [2.36]
    pos7: [1.57]
    pos8: [0.785]
    pos9: [0]