controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 250  # Hz
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - left_leg_joint
      - right_leg_joint
    command_interfaces:
      - position